export { ReactComponent as ChartIcon } from "./chartItem.svg";
export { ReactComponent as PrintIcon } from "./printIcon.svg";
export { ReactComponent as PlusIcon } from "./plusIcon.svg";
export { ReactComponent as DownloadIcon } from "./downloadIcon.svg";
export { ReactComponent as FullScreen } from "./fullScreen.svg";
export { ReactComponent as SaveIcon } from "./saveIcon.svg";
export { ReactComponent as LeftArrow } from "./leftArrow.svg"
export { ReactComponent as Dashboard } from "./dashboard.svg"
export { ReactComponent as Sales } from "./sales.svg"
export { ReactComponent as Contacts } from "./contacts.svg"
export { ReactComponent as ProjectManagement } from "./projectManagement.svg"
export { ReactComponent as Clients } from "./clients.svg"
export { ReactComponent as Subcontractors } from "./subcontractors.svg"
export { ReactComponent as Inspections } from "./inspections.svg"
export { ReactComponent as Documentation } from "./documentation.svg"
export { ReactComponent as Reports } from "./reports.svg"
export { ReactComponent as Approvals } from "./approvals.svg"
export { ReactComponent as Tasks } from "./tasks.svg"
export { ReactComponent as Notes } from "./notes.svg"
export { ReactComponent as FleetManagement } from "./fleetManagement.svg"
export { ReactComponent as Accounting } from "./accounting.svg"
export { ReactComponent as Incidents } from "./incidents.svg"
export { ReactComponent as Claim } from "./claim.svg"
export { ReactComponent as Safety } from "./safety.svg"

